name: 'Test Code for a11y issues'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pa11-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@latest
      - uses: Hesedi3l/pa11y-actions@v1
        with:
          start: test
          port: '3000'
  own-server:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        chrome-version: [latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Serve Files
      uses: Eun/http-server-action@v1
      with:
        directory: ${{ github.workspace }}
        port: 3000
    - run: npm run test:ci
  
  global-pa11y:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        chrome-version: [latest]
    steps:
      - uses: actions/checkout@v3
      - uses : actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:ci